

services:
  app:
    build: .
    container_name: genai-short-movie-app
    ports:
      - "8000:8000"
    volumes:
      - .:/FastAPI
    environment:
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_NAME=db
      - DB_HOST=db
      - DB_PORT=5432
      - OPENAI_API_KEY=${OPENAI_API_KEY}

    depends_on:
      - db
  db:
    image: postgres:13
    container_name: genai-short-movie-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
  
