

services:
  app:
    build: .
    container_name: genai-short-movie-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DB_USER=yourusername
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdatabase
      - DB_HOST=db
      - DB_PORT=5432
      - OPENAI_API_KEY=your_openai_api_key
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: genai-short-movie-db
    environment:
      - POSTGRES_USER=yourusername
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdatabase
    ports:
      - "5432:5432"
  
